apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: DOCKER_USERNAME/PROJECT_NAME:latest  # будет заменён sed
          ports:
            - containerPort: 5000
